### ISSUE TITLE
No active output found. on Wayland

### ISSUE THREAD

**Issue by viniciusfischer** [fraz0815/gptouch-python#2]
when i tri to use the script i receive this result:

<img width="623" alt="Screenshot_17" src="https://github.com/user-attachments/assets/fca32513-2ddd-4d80-b4b7-9714bb298843">

but i have one display connected via HDMI

**Comment by viniciusfischer** [comment]
![Uploading Screenshot_17.png…]()

**Comment by viniciusfischer** [comment]
<img width="623" alt="Screenshot_17" src="https://github.com/user-attachments/assets/37da4197-a709-400b-b57d-30d5d0260dc3">

**Comment by fraz0815** [comment]
use latest version and make sure user is in input group
